apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kirechain
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/kachvame/kirechain-frontend
          env:
            - name: BACKEND_URL
              value: http://kirechain-service.kirechain.svc.cluster.local:8080
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: kirechain
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
